name: erp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - Flask==3.0.0
    - Flask-SQLAlchemy==3.1.1
    - Flask-CORS==4.0.0
    - Werkzeug==3.0.1
    - python-dotenv==1.0.0

